### ISSUE TITLE
Support convention-based routing

### ISSUE THREAD

**Issue by drewschrauf** [tom-sherman/rescript-remix#4]
Great work on this repo so far! I was looking to write my own ReScript bindings then stumbled on this project.

## Issue

There are a few issues that mean Remix's convention-based routing won't work with ReScript. In particular:

- The `$` character is not a valid character in [ReScript module names](https://github.com/rescript-lang/rescript-compiler/blob/master/jscomp/ext/ext_filename.ml#L105).
- All ReScript modules must have a unique name (which means, for example, each folder can't have its own `index.res`).
- The `app/routes` directory is "special" in Remix and has the [routing conventions applied automatically](https://github.com/remix-run/remix/blob/main/packages/remix-dev/config/routesConvention.ts#L31).

Assuming that convention-based routing is within the scope of this project (it seems to be used currently), I think we need an alternative set of conventions for ReScript projects.

## Proposal

It's possible to leverage the [`routes` value of `remix.config.js`](https://remix.run/docs/en/v1/api/conventions#routes) to map any arbitrary file-system representation into a set of routes. I propose that we introduce our own routing conventions for ReScript that are inspired by standard Remix but are more compatible with ReScript.

- We use a different directory for convention-based routing. The use of `app/routes` is hardcoded in Remix but the directory can be elided entirely. I've been using `reroutes` as a placeholder but am definitely open for suggestions!
- We use only the final portion following any `_` for [basic routes](https://remix.run/docs/en/v1/api/conventions#basic-routes). This allows `blog/index.js` and `products/index.js` to be represented as `blog/blog__index.res` and `products/products__index.res` respectively. It appears that the use of double underscore is a convention in ReScript/Ocaml for module namespacing.
- We use `[slugId]` instead of `$slugId` for [dynamic route parameters](https://remix.run/docs/en/v1/api/conventions#dynamic-route-parameters). This appears to be aligned with how Next.js represents tokens. `blog/$blogId.js` would be represented as `blog/blog__[blogId].res`.
- We use `[[escape_me]]` for [escaping characters](https://remix.run/docs/en/v1/api/conventions#escaping-special-characters). This overloads the use of `[` and `]` but, unfortunately, ReScript doesn't give us many other characters to work with in file names. `jokes[.]rss.tsx` would be represented as `jokes[[.]]rss.res`.
- We use `[]` for [splat routes](https://remix.run/docs/en/v1/api/conventions#splat-routes). `blog/$.tsx` would be represented as `blog/blog__[].res`.
- We continue to use `.` for [dot delimeters](https://remix.run/docs/en/v1/api/conventions#dot-delimeters).
- We continue to use a leading `__` for [pathless layout routes](https://remix.run/docs/en/v1/api/conventions#pathless-layout-routes).

Overall, the jokes tutorial app would have the following files:

```
app
├── entry.client.res
├── entry.server.res
├── reroutes
│  ├── index.res
│  ├── jokes
│  │  ├── jokes__[jokeId].res
│  │  ├── jokes__index.res
│  │  └── jokes__new.res
│  ├── jokes.res
│  ├── jokes[[.]]rss.res
│  ├── login.res
│  └── logout.res
└── root.res
```

[I'm working on a PR with this logic](https://github.com/drewschrauf/rescript-remix-template/blob/convention-routes/remix.config.js) but wanted to make sure it aligned with your thoughts/goals for this project before opening it.

**Comment by drewschrauf** [comment]
😂 Peer dependencies, the bane of my existence. I'm [building things out here](https://github.com/drewschrauf/rescript-remix-route-conventions) if you're interested in a peek. I'll fork the repo and open a proper PR once I've got it all working.

**Comment by drewschrauf** [comment]
I was trying to test my code before opening a PR and haven't been able to get `rescript-remix` to work with `rescript-remix-template`. I've tried using `npm link` and `npm pack`/`npm install` but I keep seeing errors to the effect of:

```
FAILED: app/root.cmj
We've found a bug for you!
/home/drew/Code/rescript-remix-template/app/root.res:12:8-17
10 ┆   <meta charSet="utf-8" />
11 ┆   <meta name="viewport" content="width=device-width,initial-scale=1" />
12 ┆   <Remix.Meta />
13 ┆   <Remix.Links />
14 ┆ </head>
The value makeProps can't be found in Remix.Meta
FAILED: cannot make progress due to previous errors.
```

Have you been seeing the same issues? I'm not sure if I'm being dumb or if there's a legit issue with this module.

**Comment by tom-sherman** [comment]
Yeah these are issues I'm receiving too 😕 it's what I was referring to with peer dependency issues, could you try installing from npm?

I'm going to take another look tomorrow, I must have something setup incorrectly.

See https://forum.rescript-lang.org/t/how-to-do-peer-dependencies-when-publishing-a-rescript-npm-package/2837
